### ISSUE TITLE
Learn IOS from sample codes.

### ISSUE THREAD

**Issue by qiaosu** [qiaosu/tech_notebook#1]
#### To Do:
# 
- 2013.5.17
- [x] Custom background with font pattern [link](https://github.com/qiaosu/NoteBook/issues/4)
# 

-2013.5.20
- [ ] A custom TableViewCell
# 
- 2013.5.20
- [ ] Date Formater
# 
- 2013.5.22
- [x] SSPullToRefresh  [link](https://github.com/qiaosu/NoteBook/issues/5)
# 
- 2013.5.22
- [x] Shadow on UITextField text  [link](https://github.com/qiaosu/NoteBook/issues/6)
# 
- 2013.5.28
- [x] push/pop a viewController programmatically [link](https://github.com/qiaosu/NoteBook/issues/7)
